name: Deploy Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # 3. Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --optimize-autoloader

      # 4. Set up the environment file and generate an application key
      - name: Setup .env
        run: |
          cp .env.example .env
          php artisan key:generate --force

      # 5. Set up Bun and build front-end assets
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies and Build
        run: |
          bun install
          bun run build

      # 6. Deploy via rsync over SSH
      - name: Deploy via Rsync over SSH
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude='.env' --exclude='.htaccess' --exclude='node_modules'
          path: './' # Local directory to deploy
          remote_path: ${{ secrets.SSH_PATH }}/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}

      # 7. Run remote SSH commands to finalize deployment
      - name: Run Remote SSH Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            php artisan migrate --force
            php artisan optimize:clear
            php artisan storage:link

      # 8. Set Permissions on Directories
      - name: Set Permissions on Directories
        run: |
          chmod -R 775 storage bootstrap/cache
          chmod -R 775 storage/logs
